services:
  db:
    image: postgres:latest
    container_name: bancodedados
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  app:
    build: ./app
    container_name: backend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_PASSWORD=postgres

volumes:
  pgdata: